export { default as Error404 } from './Error404/Error404'
export { default as Movies } from './Movies/Movies'
export { default as MovieInformation } from './MovieInformation/MovieInformation'
export { default as Actors } from './Actors/Actors'
export { default as Profile } from './Profile/Profile'
export { default as NavBar } from './NavBar/NavBar'